### PR TITLE
Added pacman 6.0 support.

### PR DESCRIPTION
**Pull request by class101**
Hello @aarnt 

It possible to consider these changes to add pacman 6.0 support. Might be not perfect but I tested so far with the octopi-git package of Arch Linux and I didn't find any regression.

### CODE REVIEW

**Comment by MatMoul** [comment]
@class101 Looking to make a temporary patch on the AUR package, I've just tested the PR but when I launch octopi, I see only AUR packages after an empty line...
I've tested with the current octopi package and the last commit.
Does anyone have the same issue?

image

**Comment by MatMoul** [comment]
Switching to pacman backend seem to have solved the issue.

**Comment by class101** [comment]
Ha yes indeed good catch. I have just assumed the changes were just on Types without much but it seems I was wrong and more changed like for example the API responses. Will try to catch what is going wrong.

Thank you for sharing the workaround too.

**Comment by MatMoul** [comment]
@class11 It's a good start,
I've just updated the dev package (alpm + octopi) in AUR with the patch.

**Comment by class101** [comment]
Fixed, I forgot to add `out` statements, too much Java haha 
https://gist.github.com/class101/fa8e56b084f184ac653901aa7a646964

**Comment by MatMoul** [comment]
I've just pushed a new dev release of alpm with your last changes and it's work well for me after switching back to ALPM + pacman backend, good work !!!

@aarnt If you find some time to check the PR, it seems ready ;-)

**Comment by cimarronline** [comment]
With both commits, octopi works great for me too (with pacman 6.0). Thanks @class101!

**Comment by M1CK431** [comment]
Hi,

I have installed `octopi-dev` and `alpm_octopi_utils-dev` from AUR after the last update from @MatMoul (big thanks). I'm able to use Octopi now but I have notice a few strange characters while upgrading from the frameworks notifier:
image

Dunno if it's related to `alpm_octopi_utils` or not, but I'm sure that it happens after the pacman upgrade.

Thanks a lot for all your hard works guys, Octopi is the best GUI for pacman (and AUR).

**Comment by MatMoul** [comment]
@M1CK431 I've suspected that notifier isn't compatible with the octopi-dev but after pushing the new alpm_octopi_utils and octopi + notifiers, same issue with this strange characters...

Not sure if it is a alpm_octopi_issue or an octopi issue...

**Comment by class101** [comment]
Yes, I note this too whether using the alpm + pacman backend or pacman backend only, so I doubt `alpm_octopi_utils` is causing this. Must be something that changed in pacman around bash terminal and colors handling but unsure yet, e.g. the `TERM` environment variable or something like that.

Screenshot from 2021-06-03 23-08-05

**Comment by M1CK431** [comment]
Perhaps related to: https://git.archlinux.org/pacman.git/tree/NEWS#n16 :man_shrugging:

**Comment by aarnt** [comment]
Did you all recompiled Octopi and Notifier with yesterday's parser fixes? (Yes, there were many string bugs)

**Comment by M1CK431** [comment]
It's GMT+2:
image

**Comment by aarnt** [comment]
Ok, but this is the git commit you need: f5b9270bbdf633f3d7fe14224bb09d6b4ce4412c

I think octopi-dev pkg has 7c35dfd8457b6748a2910add59422bbb58caadbf

**Comment by M1CK431** [comment]
You are right @aarnt , I will test it ASAP and let you know

**Comment by M1CK431** [comment]
I can confirm that after rebuilding both `octopi` and `octopi-notifier-frameworks` on upstream (commit `f5b9270bbdf633f3d7fe14224bb09d6b4ce4412c`), everything works perfectly. :+1: 

Thanks A LOT! :kissing_heart:

**Comment by M1CK431** [comment]
@MatMoul I guess you forgot about updating the commit in your latest PKGBUILD update: https://aur.archlinux.org/cgit/aur.git/commit/?h=alpm_octopi_utils-dev&id=7861ae1d5f06caa5c2dbd84482eb384499881927

We are still on `2bb9349507f8155155c9b5f12b1f30e60e157d30` instead of `1e735c3a27803ca5b6470e946f9cac708143dfd9`.

I dunno how to open a pull request on git.archlinux.org but here is the diff I would like to merge.
[patch.txt](https://github.com/aarnt/alpm_octopi_utils/files/6599157/patch.txt)

**Comment by class101** [comment]
> Did you all recompiled Octopi and Notifier with yesterday's parser fixes? (Yes, there were many string bugs)

@aarnt That was this I think, I forgot to retrieve octopi-git through the paru aur helper after some tests with makepkg and so on it was no more tracked and missing few commits, thank you

**Comment by MatMoul** [comment]
@M1CK431 Thanks for the missed update of the commit after removing patch files...
I've updated it, not sure if you need to rebuild octopi-dev.

**Comment by M1CK431** [comment]
@MatMoul the PKGBUILD looks good now for `alpm_octopi_utils`, thanks :+1: 

About `octopi-dev` (and `octopi-notifier-frameworks` and probably also `octopi-notifier-qt5` I guess) a rebuild will be needed after updating there respective PKGBUILD files to use [the latest `octopi` commit](https://github.com/aarnt/octopi/commit/f5b9270bbdf633f3d7fe14224bb09d6b4ce4412c) (`f5b9270bbdf633f3d7fe14224bb09d6b4ce4412c`) in order to fix the string parsing issue [as already reported by @aarnt ](https://github.com/aarnt/alpm_octopi_utils/pull/6#issuecomment-854702543).

**Comment by MatMoul** [comment]
@M1CK431 The dev version is a dev version ... I hope everyone can rebuild these packages ...

@ALL I now suggest opening separate issues for each issue found.

**Pull request merged**
